---

name: release to master

"on":
  push:
    branches: [release]

  workflow_dispatch:

jobs:
  release2master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: versions
        run: |
          git -v

      - name: create PR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git fetch --deepen 1 origin master:refs/remotes/origin/master
          pr_body=$(git log --no-merges --oneline --pretty=format:"%h %s" origin/master..origin/release)

          pr=$(gh pr list --base master | grep "release to master")
          result=$?
          if [ $result = 0 ]; then
            echo "$pr_body" | gh pr edit $(echo "$pr" | awk '{print $1}') --body-file -
          else
            echo "$pr_body" | gh pr create --title "release to master" --base master --head release --body-file -
          fi
