---

name: release to master

"on":
  push:
    branches: [release]

  workflow_dispatch:

jobs:
  release2master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: versions
        run: |
          git -v

      - name: prepare PR
        id: prepare
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git fetch --deepen 1 origin master:refs/remotes/origin/master

          pr=$(gh pr list --base master | grep "release to master" | cat)
          echo "pr=$pr" >> $GITHUB_OUTPUT

          pr_body=$(git log --no-merges --oneline --pretty=format:"%h %s" origin/master..origin/release)
          {
            echo 'pr_body<<EOF'
            echo "$pr_body"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: PR check
        id: pr_check
        run: |
          if [ "${{steps.prepare.outputs.pr}}" == "" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: update PR
        if: steps.pr_check.outputs.exists == 'true'
        run: |
          echo "${{steps.prepare.outputs.pr_body}}" | gh pr edit $(echo "${{steps.prepare.outputs.pr}}" | awk '{print $1}') --body-file -

      - name: create PR
        if: steps.pr_check.outputs.exists == 'false'
        run: |
          echo "${{steps.prepare.outputs.pr_body}}" | gh pr create --title "release to master" --base master --head release --body-file -
